### ISSUE TITLE
thread 'main' panicked at 'already borrowed: BorrowMutError'

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/wasmtime#145]
Same wasm file and invocation as #144:

```
thread 'main' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libcore/macros.rs:18
   9: wasmtime_init_finish
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libcore/result.rs:827
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libcore/cell.rs:873
             at wasmtime-runtime/src/signalhandlers.rs:93
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/thread/local.rs:299
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/thread/local.rs:245
             at wasmtime-runtime/src/signalhandlers.rs:92
  10: wasmtime_runtime::instance::InstanceHandle::new
             at wasmtime-runtime/src/instance.rs:760
  11: wasmtime_wast::spectest::instantiate_spectest
             at wasmtime-wast/src/spectest.rs:219
  12: wasmtime::main
             at src/wasmtime.rs:238
  13: std::rt::lang_start::{{closure}}
             at /rustc/af98304b9a006e2f9a367b1f79dd7655f243c150/src/libstd/rt.rs:64
  14: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  16: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  17: main
  18: __libc_start_main
  19: _start
Process 6984 stopped
* thread #1: tid = 6984, 0x0000555555672da2 wasmtime`wasmtime_init_finish + 722 at signalhandlers.rs:70, name = 'wasmtime', stop reason = signal SIGILL: illegal instruction operand
    frame #0: 0x0000555555672da2 wasmtime`wasmtime_init_finish + 722 at signalhandlers.rs:70
   67   /// be performed per-thread. This operation may incur some overhead and
   68   /// so should be done only when needed to use wasm.
   69   #[no_mangle]
-> 70   pub extern "C" fn wasmtime_init_finish(vmctx: &mut VMContext) {
   71       if !TRAP_CONTEXT.with(|cx| cx.borrow().triedToInstallSignalHandlers) {
   72           TRAP_CONTEXT.with(|cx| {
   73               cx.borrow_mut().triedToInstallSignalHandlers = true;
```

**Comment by bjorn3** [comment]
After recompiling wasmtime from scratch it seems to work.
