### ISSUE TITLE
[wasmtime-api] Calling convention mismatch on Windows.

### ISSUE THREAD

**Issue by peterhuene** [CraneStation/wasmtime#378]
## Repro steps

On Windows:

1. Uncomment this line in `wasmtime-api/tests/import_calling_export.rs` https://github.com/CraneStation/wasmtime/blob/72ef81dd6c6c6a0a27b843f63aad0bf24c076e6d/wasmtime-api/tests/import_calling_export.rs#L7 
2. `cd wasmtime-api`
3. `cargo test`

## Expected results

The test should pass.

## Actual results

The test panics:

```
---- test_import_calling_export stdout ----
thread 'test_import_calling_export' panicked at 'failed to instantiate module: Instantiate(Link(LinkError("/imp: exported function with signature (i64 vmctx) system_v incompatible with function import with signature (i64 vmctx) windows_fastcall")))

stack backtrace:
   0: backtrace::backtrace::dbghelp::trace
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.38\src\backtrace\dbghelp.rs:88
   1: backtrace::backtrace::trace_unsynchronized<closure>
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.38\src\backtrace\mod.rs:66
   2: backtrace::backtrace::trace<closure>
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.38\src\backtrace\mod.rs:53
   3: backtrace::capture::Backtrace::create
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.38\src\capture.rs:164
   4: backtrace::capture::Backtrace::new_unresolved
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.38\src\capture.rs:158
   5: failure::backtrace::internal::InternalBacktrace::new
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.5\src\backtrace\internal.rs:44
   6: failure::backtrace::Backtrace::new
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.5\src\backtrace\mod.rs:111
   7: failure::error::error_impl::{{impl}}::from<wasmtime_jit::instantiate::SetupError>
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.5\src\error\error_impl.rs:19
   8: failure::error::{{impl}}::from<wasmtime_jit::instantiate::SetupError>
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.5\src\error\mod.rs:36
   9: wasmtime_api::instance::instantiate_in_context
             at src\instance.rs:43
  10: wasmtime_api::instance::Instance::new
             at src\instance.rs:74
  11: import_calling_export::test_import_calling_export
             at tests\import_calling_export.rs:47
  12: import_calling_export::test_import_calling_export::{{closure}}
             at tests\import_calling_export.rs:7
  13: core::ops::function::FnOnce::call_once<closure,()>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libcore\ops\function.rs:231
  14: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\liballoc\boxed.rs:746
  15: panic_unwind::__rust_maybe_catch_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libpanic_unwind\lib.rs:82
  16: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panicking.rs:275
  17: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panic.rs:394
  18: test::run_test::run_test_inner::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libtest\lib.rs:1466
  19: std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\sys_common\backtrace.rs:77
  20: std::thread::{{impl}}::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\thread\mod.rs:470
  21: std::panic::{{impl}}::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panic.rs:315
  22: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panicking.rs:296
  23: panic_unwind::__rust_maybe_catch_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libpanic_unwind\lib.rs:82
  24: std::panicking::try
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panicking.rs:275
  25: std::panic::catch_unwind
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\panic.rs:394
  26: std::thread::{{impl}}::spawn_unchecked::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libstd\thread\mod.rs:469
  27: core::ops::function::FnOnce::call_once<closure,()>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\libcore\ops\function.rs:231
  28: alloc::boxed::{{impl}}::call_once<(),FnOnce<()>>
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\liballoc\boxed.rs:746
  29: alloc::boxed::{{impl}}::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\src\liballoc\boxed.rs:746
  30: std::sys_common::thread::start_thread
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\sys_common\thread.rs:13
  31: std::sys::windows::thread::{{impl}}::new::thread_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b\/src\libstd\sys\windows\thread.rs:47
  32: BaseThreadInitThunk
  33: RtlUserThreadStart
```

**Comment by peterhuene** [comment]
We should re-enable this test as part of the fix for this panic.

**Comment by peterhuene** [comment]
See #366 for the PR containing the test.
